name: "bigbird_ner"
backend: "onnxruntime"
max_batch_size: 8

dynamic_batching {
  preferred_batch_size: [1, 2, 4, 8]
  max_queue_delay_microseconds: 5000
}

input [
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [-1]
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT64
    dims: [-1]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP32
    dims: [-1, 15]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

optimization {
  graph {
    level: 1
  }
}
